DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
dueDate DATETIME,
status VARCHAR(10) DEFAULT 'new',
description VARCHAR(256) DEFAULT NULL
);
